version: "3.7"
services:
  web:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./config/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - isuda
      - isutar
  isuda:
    build:
      context: .
      dockerfile: ./docker/api.dockerfile
      target: isuda
    environment:
      ISUDA_DB_HOST: mysql-isuda
      ISUDA_DB_PORT: 3306
      ISUDA_DB_USER: root
      ISUDA_DB_NAME: isuda
      ISUDA_DB_PASSWORD: isucon
      ISUTAR_ORIGIN: http://isutar:5001
      ISUPAM_ORIGIN: http://isupam:5050
    ports:
      - "5000:5000"
  isutar:
    build:
      context: .
      dockerfile: ./docker/api.dockerfile
      target: isutar
    environment:
      ISUTAR_DB_HOST: mysql-isutar
      ISUTAR_DB_PORT: 3306
      ISUTAR_DB_USER: root
      ISUTAR_DB_NAME: isutar
      ISUTAR_DB_PASSWORD: isucon
      ISUDA_ORIGIN: http://isuda:5000
    ports:
      - "5001:5001"
  isupam:
    build:
      context: .
      dockerfile: ./docker/isupam.dockerfile
      target: isupam
    ports:
      - "5050:5050"
  mysql-isuda:
    build:
      context: docker
      dockerfile: ./mysql.dockerfile
    ports:
      - "3306:3306"
    volumes:
      - mysql-isuda:/var/lib/mysql
      - ./db/init/isuda:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_HOST: "%"
      MYSQL_ROOT_PASSWORD: isucon
      MYSQL_DATABASE: isuda
      MYSQL_USER: isucon
      MYSQL_PASSWORD: isucon
  mysql-isutar:
    build:
      context: docker
      dockerfile: ./mysql.dockerfile
    ports:
      - "3307:3306"
    volumes:
      - mysql-isutar:/var/lib/mysql
      - ./db/init/isutar:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_HOST: "%"
      MYSQL_ROOT_PASSWORD: isucon
      MYSQL_DATABASE: isutar
      MYSQL_USER: isucon
      MYSQL_PASSWORD: isucon
volumes:
  mysql-isuda:
  mysql-isutar:
