---
- hosts: all
  become: yes
  gather_facts: no
  tags:
    - always
  tasks:
    - apt: name=nginx state=present
    - copy: src=../files/nginx.php.conf dest=/etc/nginx/nginx.php.conf owner=root mode=644
    - copy: src=../files/fastcgi_params dest=/etc/nginx/fastcgi_params owner=root mode=644
    - copy: src=../files/nginx.conf dest=/etc/nginx/nginx.conf owner=root mode=644
      notify:
        - restart nginx
    - service: name=nginx state=running enabled=true
  handlers:
    - name: restart nginx
      action: service name=nginx state=restarted
